# Generated by Django 2.2.4 on 2019-08-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('post_url', models.CharField(max_length=300)),
                ('contact_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'SUBMITTED'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], max_length=20)),
            ],
        ),
    ]
